#!/bin/sh

echo "deb http://pouncequick.420.am/~ivan/freeside-woody/ ./" >>/etc/apt/sources.list

apt-get update
apt-get install screen zsh libapache-mod-ssl libapache-mod-perl rsync \
        postgresql cvs fsh \
        liburi-perl libhtml-tagset-perl libnet-perl liblocale-codes-perl \
        libnet-whois-perl libwww-perl libbusiness-creditcard-perl \
        libmailtools-perl libtimedate-perl libdate-manip-perl \
        libfile-counterfile-perl libfreezethaw-perl libstring-approx-perl \
        libtext-template-perl libdbi-perl libdbd-pg-perl \
        libdbix-datasource-perl libdbix-dbschema-perl libnet-ssh-perl \
        libstring-shellquote-perl libnet-scp-perl libapache-asp-perl \
        libtie-ixhash-perl libtime-duration-perl \
        libhtml-widgets-selectlayers-perl libstorable-perl \
        libapache-dbi-perl libcache-cache-perl libdbd-mysql-perl

useradd freeside
su postgres -c "createuser -P freeside"

su freeside -c "createdb freeside"

#?
cd ../../..
make install-perl-modules
make create-config
freeside-adduser -c -h /usr/local/etc/freeside/htpasswd ivan
su freeside -c 'freeside-setup ivan'
su freeside -c '/home/ivan/freeside/bin/populate-msgcat ivan'
make deploy
