#!/bin/sh


wget --passive-ftp --continue ftp://apt-rpm.tuxfamily.org/apt/redhat/9/en/i386/RPMS.extra/apt-*i386.rpm
rpm -i apt*i386.rpm
cp sources.list /etc/apt/
apt-get update; apt-get update
#apt-get install apache mod_ssl mod_perl perl-CGI perl-CPAN perl-DBD-MySQL perl-DBD-Pg perl-DBI perl-DateManip perl-Digest-MD5 perl-HTML-Parser perl-HTML-Tagset perl-MIME-Base64 perl-Storable perl-TimeDate perl-URI perl-libnet perl-libwww-perl perl-suidperl rsync postgresql postgresql-docs postgresql-libs postgresql-server screen zsh lftp cvs #openssh

apt-get install perl-Devel-Symdump perl-BSD-Resource rpm-build

wget --passive-ftp --continue http://reb00t.com/linux/RPMS/redhat-9/apache/apache-1.3.28-0.n0i.src.rpm http://reb00t.com/linux/RPMS/redhat-9/mm/mm-1.2.1-0.n0i.i686.rpm http://reb00t.com/linux/RPMS/redhat-9/mm/mm-devel-1.2.1-0.n0i.i686.rpm
rpm -i mm-1.2.1-0.n0i.i686.rpm mm-devel-1.2.1-0.n0i.i686.rpm apache-1.3.28-0.n0i.src.rpm

install -d /usr/src/redhat
for a in BUILD RPMS SOURCES SPECS SRPMS; do mkdir /usr/src/redhat/$a; done
for a in athlon i386 i486 i586 i686 noarch; do mkdir /usr/src/redhat/RPMS/$a; done

cd /usr/src/redhat/SPECS  
rpmbuild -ba apache.spec

cd /usr/src/redhat/RPMS/i386
rpm -i apache-1.3.28-0.n0i.i386.rpm

apt-get install perl-CGI perl-CPAN perl-DBD-MySQL perl-DBD-Pg perl-DBI perl-DateManip perl-HTML-Parser perl-HTML-Tagset perl-TimeDate perl-URI perl-libwww-perl perl-suidperl rsync postgresql postgresql-docs postgresql-libs postgresql-server screen zsh lftp cvs #openssh

perl -MCPAN -e"install Locale::Country, Net::Whois, Business::CreditCard, \
                       Mail::Internet, File::CounterFile, FreezeThaw, \
                       String::Approx, Text::Template, DBIx::DataSource, \
                       DBIx::DBSchema, Net::SSH, String::ShellQuote, \
                       Net::SCP, Apache::ASP, Tie::IxHash, Time::Duration, \
                       HTML::Widgets::SelectLayers, Apache::DBI, Cache::Cache"

#edit /etc/init.d/httpd, add -DHAVE_PERL -DHAVE_SSL, then remove perl & ssl
# module load bits from /etc/httpd/conf/httpd.conf

/usr/sbin/useradd freeside

/sbin/chkconfig postgresql on
/etc/init.d/postgresql start

su postgres -c "createuser -P freeside"

su freeside -c "createdb freeside"

#?
cd ../../..
make install-perl-modules
make create-config
freeside-adduser -c -h /usr/local/etc/freeside/htpasswd ivan
su freeside -c 'freeside-setup ivan'
su freeside -c '/home/ivan/freeside/bin/populate-msgcat ivan'
make deploy

