#!/bin/sh

#up2date cvs perl perl-DBD-MySQL perl-DBI perl-DateManip perl-HTML-Parser \
up2date cvs perl perl-DateManip perl-HTML-Parser \
        perl-HTML-Tagset perl-URI perl-libwww-perl perl-CPAN \
        rsync screen zsh lftp cvs autoconf \
        gcc gd tetex tetex-afm tetex-dvips tetex-font tetex-latex

up2date --src rh-postgresql rh-postgresql-docs rh-postgresql-libs \
        rh-postgresql-server rh-postgresql-devel

##slony bits...
#up2date rpm-build bison flex python-devel tcl-devel readline-devel zlib-devel openssl-devel krb5-devel pam-devel
#mkdir /usr/src/redhat
#rpm -i /var/spool/up2date/rh-postgresql-*.src.rpm
#rpmbuild -bb /usr/src/redhat/SPECS/rh-postgresql.spec
#apt-get remove rh-postgresql rh-postgresql-docs rh-postgresql-libs rh-postgresql-server rh-postgresql-devel
#rpm -i /usr/src/redhat/RPMS/i386/rh-postgresql-7.3.8-2.i386.rpm /usr/src/redhat/RPMS/i386/rh-postgresql-devel-7.3.8-2.i386.rpm /usr/src/redhat/RPMS/i386/rh-postgresql-docs-7.3.8-2.i386.rpm /usr/src/redhat/RPMS/i386/rh-postgresql-libs-7.3.8-2.i386.rpm /usr/src/redhat/RPMS/i386/rh-postgresql-server-7.3.8-2.i386.rpm
#
#lftpget http://developer.postgresql.org/~wieck/slony1/download/slony1-1.0.5.tar.gz
#tar xzvf slony1-1.0.5.tar.gz
#cd slony1-1.0.5
#./configure --with-pgsourcetree=/usr/src/redhat/BUILD/postgresql-7.3.8/
#make
#make install
##edit /var/lib/pgsql/data/postgresql.conf: tcpip_socket = true
##edit /var/lib/pgsql/data/pg_hba.conf (entries for both hosts on both):
#host   freeside freeside        IP.ADDRESS   255.255.255.255 trust
##end of slony bits

perl -MCPAN -e"install Net::Whois::Raw, Business::CreditCard, \
                       File::CounterFile, String::Approx, Text::Template, \
                       FreezeThaw, DBIx::DBSchema, \
                       Net::SSH, String::ShellQuote, Net::SCP, \
                       HTML::Mason, Tie::IxHash, Time::Duration, \
                       HTML::Widgets::SelectLayers, Apache::DBI, \
                       Cache::Cache, IPC::ShareLite, Locale::SubCountry, \
                       Crypt::PasswdMD5, \
                       Locale::SubCountry, DBI, DBD::Pg, \
                       File::Temp, Storable, JavaScript::RPC::Server::CGI"

lftpget http://dag.wieers.com/packages/apt/apt-0.5.15cnc6-3.1.el3.dag.i386.rpm
rpm -i apt-0.5.15cnc6-3.1.el3.dag.i386.rpm 
apt-get update
apt-get install perl-GD perl-MailTools perl-TimeDate perl-NetAddr-IP

perl -MCPAN -e"install Chart::Base"

#apachetoolbox
apt-get remove httpd
up2date krb5-devel openssl-devel
lftpget http://umn.dl.sourceforge.net/sourceforge/apachetoolbox/Apachetoolbox-install-1.5.72.tar.gz
tar xzvf Apachetoolbox-install-1.5.72.tar.gz
cd Apachetoolbox-1.5.72
./install.sh
# export INCLUDES="-I/usr/kerberos/include"
cd apache_1.3.31;make
make certificate TYPE=dummy
make install
ln -s /usr/local/apache/bin/htpasswd /usr/local/bin
cp httpd-init /etc/init.d/httpd-freeside
chmod a+rx /etc/init.d/httpd-freeside 
/sbin/chkconfig httpd-freeside on
#end apachetoolbox

/usr/sbin/useradd freeside

/sbin/chkconfig rhdb on
/etc/init.d/rhdb start

su postgres -c "createuser -P freeside"

su freeside -c "createdb freeside"

#?
cd ../../..
make install-perl-modules
make create-config
freeside-adduser -c -h /usr/local/etc/freeside/htpasswd ivan
LANG=C su freeside -c 'freeside-setup ivan'
## do slony foo in here
##master
#su freeside -c 'pg_dump freeside' >dumps/setup.sql
#scp dumps/setup.sql othermachine:.
##slave
#su freeside -c 'psql freeside <setup.sql'
##end slony foo
su freeside -c '/home/ivan/freeside/bin/populate-msgcat ivan'
make deploy

