<?php

/**
 * @file
 * Functions for the interface to the help page
 */

/**
  * Class for help
  */
class myaccount {

  /*
   * rank (for prioritizing modules)
   */
  function rank() {

    $rank = 9;
    return $rank;
  }

  /*
   * init
   */
  function init() {
  }

  /*
   * Adds menu item to nav menu
   *
   * @param $args
   *   Common arguments
   */
  function navMenu($args) {

    $ret .= "<p><small><small><a href='" . $_SESSION['ARI_ROOT'] . "?m=myaccount&f=display'>" . _("My Account") . "</a></small></small></p><br>";

    return $ret;
  }

  /*
   * Displays stats page
   *
   * @param $args
   *   Common arguments
   */
  function display($args) {

    global $ARI_HELP_FEATURE_CODES;

    $display = new Display();

    // args
    $m = getArgument($args,'m');
    $q = getArgument($args,'q');

    $displayname = $_SESSION['ari_user']['displayname'];
    $extension = $_SESSION['ari_user']['extension'];

    // build page content
    $ret .= checkErrorMessage();

	$header_text = _("My Account");
	if (!$_SESSION['ari_user']['admin_help']) {
		$header_text .= sprintf(_(" for %s (%s)"), $displayname, $extension);
	}

    // build page content
    $ret .= checkErrorMessage();

    $ret .= $display->displayHeaderText($header_text);
    $ret .= $display->displayLine();

    $freeside = new FreesideSelfService();
    $fs_info = $freeside->customer_info( array(
      'session_id' => $_SESSION['freeside_session_id'],
    ) );
    $error = $fs_info['error'];
    if ( $error ) {
      //$_SESSION['ari_error'] = _("Incorrect Username or Password");
      $_SESSION['ari_error'] = $error; #// XXX report as ari_error???!
    }

    $ret .= $fs_info['small_custview'];
    $ret .= '<BR>';


    $ret .= '<B><A HREF="/selfservice/selfservice.cgi?session='.
            $_SESSION['freeside_session_id'].
            ';action=change_bill">Change billing address</A></B>';

    $ret .= '&nbsp;&nbsp;|&nbsp;&nbsp;';

    $ret .= '<B><A HREF="/selfservice/selfservice.cgi?session='.
            $_SESSION['freeside_session_id'].
            ';action=change_ship">Change service address</A></B>';

    $ret .= '<BR><BR>';

    $ret .= '<B><A HREF="/selfservice/selfservice.cgi?session='.
            $_SESSION['freeside_session_id'].
            ';action=change_pay">Change payment information</A></B><BR><BR>';

    return $ret;
  }

}

?>
