#!/bin/sh

( cd ..; make deploy; cd fs_selfservice )

cd FS-SelfService
perl Makefile.PL && make && make install

cd ..
kill `cat /var/run/freeside-selfservice-server.ivan.pid`; sleep 3
./freeside-selfservice-server ivan localhost

cp /home/ivan/freeside/fs_selfservice/FS-SelfService/cgi/* /var/www/MyAccount
chown freeside /var/www/MyAccount/selfservice.cgi
chmod 755 /var/www/MyAccount/selfservice.cgi
ln -s /var/www/MyAccount/selfservice.cgi /var/www/MyAccount/index.cgi || true
