#!/usr/bin/perl -w

use strict;
use FS::SelfService qw(passwd);

my $error = passwd(
  'username' => 'ivan',
  'old_password' => 'heyhoo',
  'new_password' => 'haloo',
);

if ( $error eq 'Incorrect password.' ) {
  exit;
} else {
  die $error if $error;
  die "no error";
}

