#!/usr/local/bin/perl

###
# THIS IS FROM CYBERCASH (is there a newer version?)
###

$paymentserverhost = 'localhost';
$paymentserverport = 8000;
$paymentserversecret = 'two-turntables';
use CCLib qw(sendmserver);

# first lets fake up some data 
# use time of day and pid to give me my pretend
# order number
# you obviously need to get real data from somewhere...

$oid = "test$$"; #fake order number.
$amount = 'usd 42.42';
$ramount = 'usd 24.24';
$pan = '4111111111111111';
$name = 'John Q. Doe';
$addr = '17 Richard Rd.';
$city = 'Ivyland';
$state = 'PA';
$zip = '18974';
$country = 'USA';
$exp = '7/97';


%result = &sendmserver('mauthcapture', 
                       'Order-ID', $oid,
		       'Amount', $amount,
		       'Card-Number', $pan,
		       'Card-Name', $name,
		       'Card-Address', $addr,
		       'Card-City', $city,
		       'Card-State', $state,
		       'Card-Zip', $zip,
		       'Card-Country', $country,
		       'Card-Exp', $exp);

#
# just dump results to stdout.
# you should process them...
# to allow results to affect operation of your fulfillment...
#
foreach (keys(%result)) {
   print " $_ ==> $result{$_}\n";
}

print "\n";

exit;

$trans=$result{'MTransactionNumber'};
$code=$result{'MRetrievalCode'};

%result = &sendmserver('return',
                        'Order-ID', $oid,
			'Return-Amount',$ramount,
			'Amount',$amount,
			);

foreach (keys(%result)) {
   print " $_ ==> $result{$_}\n";
}

