#!/bin/sh

# based on install/redhat/9/INSTALL

# apt for SuSE howto: http://linux01.gwdg.de/apt4rpm/

for file in ftp://ftp.gwdg.de/pub/linux/suse/apt/SuSE/9.0-i386/RPMS.suser-rbos/apt-0.5.5cnc6-rb6.i586.rpm ftp://ftp.gwdg.de/pub/linux/suse/apt/SuSE/9.0-i386/RPMS.suser-rbos/apt-libs-0.5.5cnc6-rb6.i586.rpm ftp://ftp.gwdg.de/pub/linux/suse/apt/SuSE/9.0-i386/RPMS.suser-rbos/lua-5.0-rb3.i586.rpm; do
  curl -C - -o `basename $file` $file
done

rpm -i lua-5.0-rb3.i586.rpm
rpm -i apt-libs-0.5.5cnc6-rb6.i586.rpm
rpm -i apt-0.5.5cnc6-rb6.i586.rpm

perl -pi.bak -e 's/386 update/386 base update/' /etc/apt/sources.list

apt-get update; apt-get update

apt-get install apache mod_ssl mod_perl perl-DBI perl-Msql-Mysql-modules perl-DBD-Pg perl-DateManip perl-HTML-Parser perl-HTML-Tagset perl-TimeDate perl-URI perl-libwww-perl perl-Apache-DBI perl-Apache-ASP perl-GD perl-MailTools perl-Tie-IxHash rsync postgresql postgresql-docs postgresql-libs postgresql-server postgresql-devel screen zsh lftp wget cvs make gcc

perl -MCPAN -e"install DBD::Pg, Net::Whois, Business::CreditCard, \
                       File::CounterFile, FreezeThaw, String::Approx, \
                       Text::Template, DBIx::DataSource, DBIx::DBSchema, \
                       Net::SSH, String::ShellQuote, Net::SCP, \
                       Time::Duration, HTML::Widgets::SelectLayers, \
                       Cache::Cache, Test::Pod, NetAddr::IP, IPC::ShareLite, \
                       Chart::LinesPoints"

/usr/sbin/useradd freeside

/sbin/chkconfig postgresql on
/etc/init.d/postgresql start

/sbin/chkconfig apache on
#/etc/init.d/apache start

su postgres -c "createuser -P freeside"

su freeside -c "createdb freeside"

#?
cd ../../..
make install-perl-modules
make create-config
freeside-adduser -c -h /usr/local/etc/freeside/htpasswd ivan
su freeside -c 'freeside-setup ivan'
su freeside -c '/home/ivan/freeside/bin/populate-msgcat ivan'
make deploy




