#!/bin/sh

wget --passive-ftp --continue http://download.fedora.us/fedora/fedora/2/i386/RPMS.stable/apt-0.5.15cnc6-0.fdr.11.2.i386.rpm
rpm -i apt*i386.rpm

wget --continue http://atrpms.physik.fu-berlin.de/RPM-GPG-KEY.atrpms
rpm --import RPM-GPG-KEY.atrpms
wget --continue http://dag.wieers.com/packages/RPM-GPG-KEY.dag.txt
rpm --import RPM-GPG-KEY.dag.txt

#echo 'RPM::Allow-Duplicated { "^db4$"; };' >>/etc/apt/apt.conf

#might need to uncomment
#  GPG-Check "false";
#in /etc/apt/apt.conf

apt-get update
cp sources.list /etc/apt/sources.list
rm /etc/apt/sources.list.d/mirror-select.list
apt-get update

apt-get remove httpd mod_perl

apt-get install perl-Devel-Symdump perl-BSD-Resource perl-DBD-MySQL perl-DBI perl-DateManip perl-HTML-Parser perl-HTML-Tagset perl-TimeDate perl-URI perl-libwww-perl perl-suidperl rsync postgresql postgresql-docs postgresql-libs postgresql-server postgresql-devel screen zsh lftp cvs gcc gd perl-GD perl-MailTools perl-FreezeThaw perl-NetAddr-IP perl-Chart perl-Text-Template perl-Cache-Cache

#for rt
#apt-get install perl-Apache-Session perl-MIME-tools perl-TermReadKey perl-MLDBM perl-MLDBM-Sync

perl -MCPAN -e"install Net::Whois::Raw, Business::CreditCard, \
                       File::CounterFile, String::Approx, Text::Template, \
                       DBIx::DataSource, DBIx::DBSchema, Net::SSH, \
                       String::ShellQuote, Net::SCP, HTML::Mason, \
                       Tie::IxHash, Time::Duration, \
                       HTML::Widgets::SelectLayers, Apache::DBI, \
                       Locale::SubCountry, \
                       DBD::Pg, Crypt::PasswdMD5 "


#apachetoolbox
#lftpget http://umn.dl.sourceforge.net/sourceforge/apachetoolbox/Apachetoolbox-install-1.5.72.tar.gz
#apache config
#apache init script 

/usr/sbin/useradd freeside
chsh freeside -s /bin/bash

/sbin/chkconfig postgresql on
/etc/init.d/postgresql start

echo -e '\n\ny\nn' | su postgres -c "createuser -P freeside"

su freeside -c "createdb freeside"

#?
cd ../../..
make install-perl-modules
make create-config
ln -s /usr/local/apache/bin/htpasswd /usr/local/bin/
freeside-adduser -c -h /usr/local/etc/freeside/htpasswd ivan
su freeside -c 'freeside-setup ivan'
su freeside -c '/home/ivan/freeside/bin/populate-msgcat ivan'
make deploy

