#!/bin/sh

wget --passive-ftp ftp://apt-rpm.tuxfamily.org/apt/redhat/7.3/en/i386/RPMS.extra/apt-*i386.rpm
rpm -i apt*i386.rpm
cp sources.list /etc/apt/
apt-get update; apt-get update
apt-get install apache mod_ssl mod_perl perl-CGI perl-CPAN perl-DBD-MySQL perl-DBD-Pg perl-DBI perl-DateManip perl-Digest-MD5 perl-HTML-Parser perl-HTML-Tagset perl-MIME-Base64 perl-Storable perl-TimeDate perl-URI perl-libnet perl-libwww-perl perl-suidperl rsync postgresql postgresql-docs postgresql-libs postgresql-server screen zsh lftp cvs #openssh

wget --passive-ftp --continue http://download.atrpms.net/production/packages/redhat-7.3-i386/atrpms/atrpms-51-1.rh7.3.at.noarch.rpm http://download.atrpms.net/production/packages/redhat-7.3-i386/atrpms/atrpms-package-config-51-1.rh7.3.at.noarch.rpm http://download.atrpms.net/production/packages/redhat-7.3-i386/atrpms/gd-2.0.15-1_6.rh7.3.at.i386.rpm http://download.atrpms.net/production/packages/redhat-7.3-i386/atrpms/gd-devel-2.0.15-1_6.rh7.3.at.i386.rpm http://download.atrpms.net/production/packages/redhat-7.3-i386/atrpms/perl-GD-2.11-7.rh7.3.at.i386.rpm

#rpm -i atrpms-package-config-51-1.rh7.3.at.noarch.rpm
rpm -i atrpms-51-1.rh7.3.at.noarch.rpm
rpm -i gd-2.0.15-1_6.rh7.3.at.i386.rpm 
rpm -i perl-GD-2.11-7.rh7.3.at.i386.rpm 

perl -MCPAN -e"install Locale::Country, Net::Whois, Business::CreditCard, \
                       Mail::Internet, File::CounterFile, FreezeThaw, \
                       String::Approx, Text::Template, DBIx::DataSource, \
                       DBIx::DBSchema, Net::SSH, String::ShellQuote, \
                       Net::SCP, Apache::ASP, Tie::IxHash, Time::Duration, \
                       HTML::Widgets::SelectLayers, Apache::DBI, Cache::Cache"

useradd freeside

chkconfig postgresql on
/etc/init.d/postgresql start

su postgres -c "createuser -P freeside"

su freeside -c "createdb freeside"

#?
cd ../..
make install-perl-modules
make create-config
freeside-adduser -c -h /usr/local/etc/freeside/htpasswd ivan
su freeside -c 'freeside-setup ivan'
su freeside -c '/home/ivan/freeside/bin/populate-msgcat ivan'
make deploy

