#! /bin/sh
#
# chkconfig: 345 86 16
# description: Freeside daemons

QUEUED_USER=%%%QUEUED_USER%%%

FREESIDE_PATH="%%%FREESIDE_PATH%%%"

SELFSERVICE_USER=%%%SELFSERVICE_USER%%%
SELFSERVICE_MACHINE=%%%SELFSERVICE_MACHINE%%%

case "$1" in
  start)
        # Start daemons.
        echo -n "Starting freeside-queued: "
        freeside-queued $QUEUED_USER
        echo "done."

        echo -n "Starting freeside-selfservice-server: "
        freeside-selfservice-server $SELFSERVICE_USER $SELFSERVICE_MACHINE
        echo "done."

        ;;
  stop)
        # Stop daemons.
        echo -n "Stopping freeside-queued: "
        kill `cat /var/run/freeside-queued.pid`
        echo "done."

        echo -n "Stopping freeside-selfservice-server: "
        kill `cat /var/run/freeside-selfservice-server.$SELFSERVICE_USER.pid`
        echo "done."
        ;;

  restart)
        $0 stop
        $0 start
        ;;
  *)
        echo "Usage: freeside {start|stop|restart}"
        exit 1
esac

exit 0

