#!/bin/sh

wget --passive-ftp --continue http://download.fedora.us/fedora/fedora/1/i386/RPMS.stable/apt-0.5.15cnc5-0.fdr.10.1.i386.rpm
rpm -i apt*i386.rpm

cp sources.list /etc/apt/sources.list

apt-get update

apt-get install perl-Devel-Symdump perl-BSD-Resource

wget --passive-ftp --continue http://linux.reb00t.com/fedora-current/RPMS/apache-1.3.29-1.n0i.2.MPSSL.i686.rpm http://linux.reb00t.com/fedora-current/RPMS/mm-1.3.0-0.n0i.2.i686.rpm http://mirrors.kernel.org/fedora.us/fedora/fedora/1.91/i386/RPMS.os/db4-4.2.52-3.1.i386.rpm

apt-get remove httpd mod_perl

rpm -i mm-1.3.0-0.n0i.2.i686.rpm db4-4.2.52-3.1.i386.rpm apache-1.3.29-1.n0i.2.MPSSL.i686.rpm

/sbin/chkconfig httpd on

#edit /etc/httpd/conf/httpd.conf, remove mod_auth_db LoadMoudle and AddModule

echo 'OPTIONS="-DHAVE_PERL -DHAVE_SSL"' >>/etc/sysconfig/apache

/etc/init.d/httpd start

echo 'RPM::Allow-Duplicated { "^db4$"; };' >>/etc/apt/apt.conf

wget --continue http://atrpms.physik.fu-berlin.de/RPM-GPG-KEY.atrpms
rpm --import RPM-GPG-KEY.atrpms
wget --continue http://dag.wieers.com/packages/RPM-GPG-KEY.dag.txt
rpm --import RPM-GPG-KEY.dag.txt

apt-get install perl-DBD-MySQL perl-DBI perl-DateManip perl-HTML-Parser perl-HTML-Tagset perl-TimeDate perl-URI perl-libwww-perl perl-suidperl rsync postgresql postgresql-docs postgresql-libs postgresql-server postgresql-devel screen zsh lftp cvs gcc gd perl-GD perl-MailTools perl-FreezeThaw perl-NetAddr-IP perl-Chart 

perl -MCPAN -e"install Net::Whois::Raw, Business::CreditCard, \
                       File::CounterFile, String::Approx, Text::Template, \
                       DBIx::DataSource, DBIx::DBSchema, Net::SSH, \
                       String::ShellQuote, Net::SCP, Apache::ASP, \
                       Tie::IxHash, Time::Duration, \
                       HTML::Widgets::SelectLayers, Apache::DBI, \
                       Cache::Cache, IPC::ShareLite, Locale::SubCountry, \
                       DBD::Pg, Crypt::PasswdMD5 "


#remove perl & ssl LoadModule lines from /etc/httpd/conf/httpd.conf
#as they're statically linked (?)

/usr/sbin/useradd freeside
chsh freeside -s /bin/bash

/sbin/chkconfig postgresql on
/etc/init.d/postgresql start

echo -e '\n\ny\nn" | su postgres -c "createuser -P freeside"

su freeside -c "createdb freeside"

#?
cd ../../..
make install-perl-modules
make create-config
freeside-adduser -c -h /usr/local/etc/freeside/htpasswd ivan
su freeside -c 'freeside-setup ivan'
su freeside -c '/home/ivan/freeside/bin/populate-msgcat ivan'
make deploy

